version: '3'
services:
  app:
    image: my-spring-boot-app
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/yourdatabase
      DB_USERNAME: yourusername
      DB_PASSWORD: yourpassword
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: yourdatabase
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
